### ISSUE TITLE
Some apps crashing

### ISSUE THREAD

**Issue by chematelegram** [crdroidandroid/android_libcore#2]
Some apps like e.g. [Bilibili](https://play.google.com/store/apps/details?id=com.pkfw.bilihelper.android)  are crashing when they are started after this commit:

https://github.com/crdroidandroid/android_libcore/commit/ea826728d1b5b3833d5b677e4b53e66a10cf30cc

Reverting the commit makes the apps work without issues. This is the log for the crash:

https://paste.crdroid.net/xnaY0S

Thanks in advance

**Comment by gwolf2u** [comment]
@ShevT care the check this out please

**Comment by ShevT** [comment]
I do not observe any problems, as well as my users. If they really are, then we remove this commit.

**Comment by chematelegram** [comment]
> I do not observe any problems, as well as my users. If they really are, then we remove this commit.

No offense intended in my question but, did you test this Bilibili app which I linked in my first post?

**Comment by ShevT** [comment]
> No offense intended in my question but, did you test this Bilibili app which I linked in my first post?

No. I can't find this app on Play Market. The link does not open through the browser, because. I live in Russia and Google has blocked this possibility.

**Comment by neobuddy89** [comment]
I tested this. The app crashed and the revert resolved crash . Will revert this commit.

**Comment by chematelegram** [comment]
Many thanks for this and all the good work the team put in the ROM.
